permalink: /:categories/:title.html
url: "http://dsfinan.github.io/"
full_name: "Daniel Finan"
first_name: "Daniel"
last_name: "Finan"
blog_title: "Time Suck "
author_img_name_path: "/images/users/user.jpg"
disqus_shortname: "dsfinan"
copyright_year: "2014"
google_analytics_code: ""
aboutme: "I started writing Star Trek choose your own adventure programs in BASIC on an Apple II back in the early 80's.  Likely after visiting my brother in college who showed me how to play the Mike Mayfield’s Start Trek on a VAX workstation."
twitter: "dsfinan"
github: "dsfinan"
facebook: ""
linkined_url: "www.linkedin.com/in/dsfinan/"
