permalink: /:categories/:title.html
url: "http://dsfinan.github.io/"
full_name: "Daniel Finan"
first_name: "Daniel Name"
last_name: "Finan"
blog_title: "Time Suck "
author_img_name_path: "/images/users/user.jpg"
disqus_shortname: "dsfinan"
copyright_year: "2014"
google_analytics_code: ""
aboutme: "Something about the author here"
twitter: "dsfinan"
github: "dsfinan"
facebook: ""
linkined_url: "www.linkedin.com/in/dsfinan/"
